config/routes.rb
Rails.application.routes.draw do
  resources :notes
  resources :students
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "students#index"
  post 'notes/:id', to: 'notes#create'

  post '/log_in', to: 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :student
  validates_associated :student
  #validations go here
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :note
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :student
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    def set_student
      @student = Student.find(params[:id])
    end 

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:category, :desciption, :status, :student_id)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_student, only: %i[ show edit update destroy ]

 

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :grade, :teacher, :user_id)
    end
end

 
#When i fill a form for a student I dont want manually enter the user_id, how 
#where do i delete the field?in validations and on the views

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #added this action because i am playing with it.
    #create a view file for index
    def index
        @user = User.all
    end

    def create
        User.create(user_params)
    end

    private
    def user_params
        params.permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaterFriend 
    </title>
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="jumbotron">
    
      <%= render 'shared/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>

  <% if !flash[:alert].nil? %>
    <p class="my_alert"><%= flash[:alert] %></p>
  <% end %>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :desciption %>
    <%= form.text_area :desciption %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

 

  <div class="drop_menu">
  <%= "Student:" %>
  <br>
    <%= form.collection_select :student_id, Student.all, :id, :name, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_notes.html.erb
#this view intends to show the notes that each kid have

<p>
  <strong>Type:</strong>
  <%= @note.category %>
</p>

<p>
  <strong>Desciption:</strong>
  <%= @note.desciption %>
</p>

<p>
  <strong>Status:</strong>
  <%= @note.status %>
</p>

<p>
  <strong>Student:</strong>
  <%= @note.student_id %>
</p>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note  %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Desciption</th>
      <th>Status</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.category %></td>
        <td><%= note.desciption %></td>
        <td><%= note.status %></td>
        <td><%= note.student_id %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

<br>

<%= link_to 'Back to Students', students_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @note.type %>
</p>

<p>
  <strong>Desciption:</strong>
  <%= @note.desciption %>
</p>

<p>
  <strong>Status:</strong>
  <%= @note.status %>
</p>

<p>
  <strong>Student:</strong>
  <%= @note.student_id %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/shared/_navbar.html.erb
<% if false %>
 #this is a partial that will contain the NAVBAR with some IF statements to 
 #show that if the user is logged in then it should have some menu options
 #that say Sign out
 #and if the user is not logged in yet then the menu options will say Sign up or Log in
 #NOTE:the sign out is not destroying the session yet, manually deleting cookies to logout

<% end %>



<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Later Friend</a>
    <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto ">
        <% if user_signed_in? %>
            <li class="nav-item active">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete%>
            </li>
        <% else %>
           <li class="nav-item active">
             <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
           </li>
           <li class="nav-item active">
           <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %> 
           </li>
           
           </div>
        <% end %>
      </ul>
   
  </div>
</nav>

 

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.text_field :grade %>
  </div>

  <div class="field">
    <%= form.label :teacher %>
    <%= form.text_field :teacher %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_welcome.html.erb
<div class="card">
  <div class="card-body text-center">
  <h1> Welcome back <%= current_user.email%> </h1>
  <h2>Today is <%= Time.now.strftime("%m/%d/%Y") %></h2>
  </div>
</div>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<%= render "students/welcome" %>



<h2>Students</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Grade</th>
      <th>Teacher</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.grade %></td>
        <td><%= student.teacher %></td>
        <td><%= student.user_id %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'New Note', new_note_path %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'All notes', notes_path %>

<% if false %>

<%# link_to 'New Student', new_student_path %>
<% end %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card shadow p-4 mb-5 bg-white rounded">

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @student.grade %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @student.teacher %>
</p>

<p>
  <strong>User:</strong>
  <%= @student.user_id %>
</p>

</div>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>